import { DashboardStats, Scan, ScanFinding, Target, User } from '../types';

export const FALLBACK_USER: User = {
  id: 'usr_secops_demo_01',
  email: 'demo@cyvera.io',
  username: 'secops_demo',
  is_active: true,
  is_verified: true,
  created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
};

export const FALLBACK_TARGETS: Target[] = [
  {
    id: 'tgt_01',
    user_id: FALLBACK_USER.id,
    name: 'OWASP Juice Shop (Staging)',
    url: 'https://juice-shop.staging.internal',
    description: 'Vulnerable test environment for modern web security validation and DAST verification.',
    is_active: true,
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    total_scans: 8,
    latest_score: 62,
  },
  {
    id: 'tgt_02',
    user_id: FALLBACK_USER.id,
    name: 'FinTech Core API Gateway',
    url: 'https://api.fintech-vault.io',
    description: 'Production banking API gateway routing payments and microservices.',
    is_active: true,
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    total_scans: 12,
    latest_score: 91,
  },
  {
    id: 'tgt_03',
    user_id: FALLBACK_USER.id,
    name: 'SecOps Customer Portal',
    url: 'https://portal.cyvera.io',
    description: 'Main authentication portal and user dashboard for enterprise security teams.',
    is_active: true,
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    total_scans: 4,
    latest_score: 88,
  },
];

export const FALLBACK_FINDINGS: ScanFinding[] = [
  {
    id: 'fnd_01',
    scan_id: 'scn_01',
    vulnerability_id: 'vuln_sql_01',
    severity: 'critical',
    risk_score: 9.8,
    confidence: 'High',
    affected_url: 'https://juice-shop.staging.internal/rest/products/search?q=',
    http_method: 'GET',
    parameter: 'q',
    attack: "') UNION SELECT id, email, password FROM Users--",
    evidence: 'SQL syntax error: unexpected token UNION in query context.',
    other_info: 'Database backend identified as SQLite 3 / PostgreSQL 15.',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    vulnerability: {
      id: 'vuln_sql_01',
      plugin_id: '40018',
      name: 'SQL Injection in Search Query Endpoint',
      description: 'SQL injection occurs when untrusted user input is directly concatenated into a database query without parameterized preparation.',
      solution: 'Use parameterized queries / prepared statements (e.g. ORM or parameterized SQL placeholders) and sanitize input filters.',
      reference: 'https://owasp.org/www-community/attacks/SQL_Injection',
      owasp_category: 'A03:2021 - Injection',
      cwe_id: 89,
      wasc_id: 19,
      created_at: new Date().toISOString(),
    },
    ai_analysis: {
      id: 'ai_01',
      finding_id: 'fnd_01',
      explanation: 'The parameter `q` is directly evaluated in a raw database query string. The payload demonstrated arbitrary table union and exfiltration capability.',
      why_it_matters: 'An unauthenticated adversary can extract all user password hashes, tokens, and PII data from the underlying database.',
      potential_impact: 'Full database compromise, horizontal privilege escalation, and regulatory non-compliance.',
      evidence_interpretation: 'The scanner received a structured database error confirming the injected SQL statement was parsed by the database engine.',
      remediation: 'Migrate the query to parameterized queries: `SELECT * FROM products WHERE name ILIKE $1`.',
      fix_guidance: '1. Locate search route handler.\n2. Replace raw concatenation with parameterized SQL placeholder binding.\n3. Add unit test asserting quote escaping.',
      model_version: 'Cyvera SecOps Gemini AI Engine v2.0',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'fnd_02',
    scan_id: 'scn_01',
    vulnerability_id: 'vuln_xss_02',
    severity: 'high',
    risk_score: 8.2,
    confidence: 'High',
    affected_url: 'https://juice-shop.staging.internal/#/contact',
    http_method: 'POST',
    parameter: 'comment',
    attack: '<iframe src="javascript:alert(`Cyvera-XSS`)">',
    evidence: 'Payload reflected without HTML encoding in document body.',
    other_info: 'DOM-based reflection in feedback preview window.',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    vulnerability: {
      id: 'vuln_xss_02',
      plugin_id: '40012',
      name: 'Reflected Cross-Site Scripting (XSS)',
      description: 'The application reflects user-supplied data into the web page without sufficient context-aware escaping or sanitization.',
      solution: 'Implement robust Content Security Policy (CSP) and sanitize HTML inputs using DOMPurify or framework native escaping.',
      reference: 'https://owasp.org/www-community/attacks/xss/',
      owasp_category: 'A03:2021 - Injection',
      cwe_id: 79,
      wasc_id: 8,
      created_at: new Date().toISOString(),
    },
    ai_analysis: {
      id: 'ai_02',
      finding_id: 'fnd_02',
      explanation: 'The feedback form renders raw HTML directly via innerHTML or unescaped template literals.',
      why_it_matters: 'Attackers can execute arbitrary JavaScript in the victim\'s browser session, hijacking authentication tokens and performing CSRF actions.',
      potential_impact: 'Session hijacking, client-side data exfiltration, phishing overlays.',
      remediation: 'Sanitize with DOMPurify or use React text node binding rather than dangerouslySetInnerHTML.',
      fix_guidance: 'Wrap feedback preview in `DOMPurify.sanitize(input)` before rendering.',
      model_version: 'Cyvera SecOps Gemini AI Engine v2.0',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'fnd_03',
    scan_id: 'scn_01',
    vulnerability_id: 'vuln_cors_03',
    severity: 'medium',
    risk_score: 5.7,
    confidence: 'Medium',
    affected_url: 'https://juice-shop.staging.internal/api/Users',
    http_method: 'OPTIONS',
    parameter: 'Origin',
    attack: 'Origin: https://evil-attacker.com',
    evidence: 'Access-Control-Allow-Origin: https://evil-attacker.com with Access-Control-Allow-Credentials: true',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    vulnerability: {
      id: 'vuln_cors_03',
      plugin_id: '10045',
      name: 'Overly Permissive CORS Origin Reflection',
      description: 'The server reflects arbitrary requested origins in the Access-Control-Allow-Origin header while enabling credentials.',
      solution: 'Restrict CORS origins to an explicit trusted whitelist and reject wildcard/reflected untrusted origins.',
      reference: 'https://portswigger.net/web-security/cors',
      owasp_category: 'A01:2021 - Broken Access Control',
      cwe_id: 942,
      created_at: new Date().toISOString(),
    },
    ai_analysis: {
      id: 'ai_03',
      finding_id: 'fnd_03',
      explanation: 'The CORS middleware dynamically mirrors the incoming Origin header while allowing cookies/credentials.',
      why_it_matters: 'Any malicious website visited by an authenticated user can read sensitive API responses.',
      potential_impact: 'Unauthorized cross-origin read of confidential user profile data.',
      remediation: 'Configure an explicit array of allowed domains in CORS middleware configuration.',
      fix_guidance: 'In CORS middleware configuration: `cors({ origin: ["https://cyvera.io"], credentials: true })`.',
      model_version: 'Cyvera SecOps Gemini AI Engine v2.0',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'fnd_04',
    scan_id: 'scn_01',
    vulnerability_id: 'vuln_csp_04',
    severity: 'low',
    risk_score: 3.4,
    confidence: 'High',
    affected_url: 'https://juice-shop.staging.internal/',
    http_method: 'GET',
    evidence: 'Content-Security-Policy header is missing in response headers.',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    vulnerability: {
      id: 'vuln_csp_04',
      plugin_id: '10038',
      name: 'Missing Content-Security-Policy (CSP) Header',
      description: 'CSP provides a defense-in-depth layer preventing unauthorized script execution, framing, and data injections.',
      solution: 'Set a strong Content-Security-Policy HTTP header.',
      reference: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
      owasp_category: 'A05:2021 - Security Misconfiguration',
      cwe_id: 693,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'fnd_05',
    scan_id: 'scn_01',
    vulnerability_id: 'vuln_info_05',
    severity: 'informational',
    risk_score: 1.0,
    confidence: 'High',
    affected_url: 'https://juice-shop.staging.internal/',
    http_method: 'GET',
    evidence: 'Server: Express/4.18.2, X-Powered-By: Express',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    vulnerability: {
      id: 'vuln_info_05',
      plugin_id: '10023',
      name: 'Server Technology Banner Disclosure (X-Powered-By)',
      description: 'Revealing exact backend framework and web server versions helps attackers target known CVEs.',
      solution: 'Disable `X-Powered-By` header (e.g. `app.disable("x-powered-by")`).',
      reference: 'https://owasp.org/www-project-web-security-testing-guide/',
      owasp_category: 'A05:2021 - Security Misconfiguration',
      cwe_id: 200,
      created_at: new Date().toISOString(),
    },
  },
];

export const FALLBACK_SCANS: Scan[] = [
  {
    id: 'scn_01',
    target_id: 'tgt_01',
    user_id: FALLBACK_USER.id,
    target_name: 'OWASP Juice Shop (Staging)',
    target_url: 'https://juice-shop.staging.internal',
    status: 'completed',
    scan_type: 'full',
    scan_engine: 'zap',
    progress: 100,
    security_score: 62,
    severity_breakdown: {
      critical: 1,
      high: 1,
      medium: 1,
      low: 1,
      informational: 1,
      total: 5,
    },
    started_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1.8 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    findings: FALLBACK_FINDINGS,
  },
  {
    id: 'scn_02',
    target_id: 'tgt_02',
    user_id: FALLBACK_USER.id,
    target_name: 'FinTech Core API Gateway',
    target_url: 'https://api.fintech-vault.io',
    status: 'completed',
    scan_type: 'passive',
    scan_engine: 'zap',
    progress: 100,
    security_score: 91,
    severity_breakdown: {
      critical: 0,
      high: 0,
      medium: 1,
      low: 2,
      informational: 4,
      total: 7,
    },
    started_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 23.8 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    findings: FALLBACK_FINDINGS.slice(2),
  },
  {
    id: 'scn_03',
    target_id: 'tgt_03',
    user_id: FALLBACK_USER.id,
    target_name: 'SecOps Customer Portal',
    target_url: 'https://portal.cyvera.io',
    status: 'completed',
    scan_type: 'active',
    scan_engine: 'fallback',
    progress: 100,
    security_score: 88,
    severity_breakdown: {
      critical: 0,
      high: 1,
      medium: 2,
      low: 3,
      informational: 2,
      total: 8,
    },
    started_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 47.7 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    findings: FALLBACK_FINDINGS.slice(1),
  },
];

export const FALLBACK_DASHBOARD_STATS: DashboardStats = {
  total_scans: 14,
  total_targets: 3,
  latest_security_score: 84,
  average_security_score: 80,
  severity_breakdown: {
    critical: 1,
    high: 2,
    medium: 4,
    low: 6,
    informational: 7,
    total: 20,
  },
  owasp_distribution: [
    { category: 'A03: Injection (SQL/XSS)', count: 2 },
    { category: 'A01: Broken Access Control', count: 1 },
    { category: 'A05: Security Misconfiguration', count: 2 },
    { category: 'A07: Identification & Auth Failures', count: 1 },
    { category: 'A09: Security Logging & Monitoring', count: 1 },
  ],
  recent_scans: FALLBACK_SCANS,
  score_trends: [
    { date: '01 Mar', scan_id: 'scn_03', target_name: 'SecOps Customer Portal', score: 88 },
    { date: '03 Mar', scan_id: 'scn_02', target_name: 'FinTech Core API Gateway', score: 91 },
    { date: '07 Mar', scan_id: 'scn_01', target_name: 'OWASP Juice Shop', score: 62 },
  ],
};
